DROP DATABASE IF EXISTS music;

CREATE DATABASE music; /* Creation of the database */

\c music

CREATE TABLE PEOPLE (
    PersonName VARCHAR(20) PRIMARY KEY,
    BirthYear INTEGER NOT NULL
);

CREATE TABLE ALBUMS (
    AlbumId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    AlbumTitle VARCHAR(50) NOT NULL,
    AlbumYear INTEGER NOT NULL
);

CREATE TABLE SONGS (
    SongId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SongTitle VARCHAR(50) NOT NULL,
    SongYear INTEGER
);

CREATE TABLE ALBUM_SONGS (
    AlbumId INTEGER REFERENCES ALBUMS(AlbumId) ON DELETE CASCADE ON UPDATE CASCADE,
    TrackId INTEGER,
    SongId INTEGER NOT NULL REFERENCES SONGS(SongId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(AlbumId, TrackId),
    UNIQUE(AlbumId, SongId)
);

CREATE TABLE SONG_AUTHORS (
    PersonName VARCHAR(20) REFERENCES PEOPLE(PersonName) ON DELETE CASCADE ON UPDATE CASCADE,
    SongId INTEGER REFERENCES SONGS(SongId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(PersonName, SongId)
);

CREATE TABLE SONG_SINGERS (
    PersonName VARCHAR(20) REFERENCES PEOPLE(PersonName) ON DELETE CASCADE ON UPDATE CASCADE,
    SongId INTEGER REFERENCES SONGS(SongId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(PersonName, SongId)
);


/* Inserts have been AI-generated. */

-- Inserts for the PEOPLE table
INSERT INTO PEOPLE (PersonName, BirthYear) VALUES('Mike Dean', NULL),
('WondaGurl', NULL),
('Gunna', NULL),
('Don Toliver', NULL),
('Sheck Wes', NULL),
('Philip Bailey', NULL),
('James Blake', NULL),
('Kid Cudi', 1984),
('The Weeknd', NULL),
('Stevie Wonder', NULL),
('Swae Lee', NULL),
('Juice Wrld', NULL);

-- Inserts for the ALBUMS table
INSERT INTO ALBUMS (AlbumTitle, AlbumYear) VALUES ('ASTROWORLD', 2018);

-- Inserts for the SONGS table
INSERT INTO SONGS (SongTitle, SongYear) VALUES
('STARGAZING', 2018),
('CAROUSEL', 2018),
('SICKO MODE', 2018),
('R.I.P. SCREW', 2018),
('STOP TRYING TO BE GOD', 2018),
('NO BYSTANDERS', 2018),
('SKELETONS', 2018),
('WAKE UP', 2018),
('5% TINT', 2018),
('NC-17', 2018),
('ASTROTHUNDER', 2018),
('YOSEMITE', 2018),
('CAN`T SAY', 2018),
('WHO? WHAT!', 2018),
('BUTTERFLY EFFECT', 2018),
('HOUSTONFORNICATION', 2018),
('COFFEE BEAN', 2018);

-- Inserts for the ALBUM_SONGS table
INSERT INTO ALBUM_SONGS (AlbumId, TrackId, SongId) VALUES
(1, 1, 1),
(1, 2, 2),
(1, 3, 3),
(1, 4, 4),
(1, 5, 5),
(1, 6, 6),
(1, 7, 7),
(1, 8, 8),
(1, 9, 9),
(1, 10, 10),
(1, 11, 11),
(1, 12, 12),
(1, 13, 13),
(1, 14, 14),
(1, 15, 15),
(1, 16, 16),
(1, 17, 17);

-- Inserts for the SONG_AUTHORS table
INSERT INTO SONG_AUTHORS (PersonName, SongId) VALUES
('Travis Scott', 1),
('Travis Scott', 2),
('Travis Scott', 3),
('Travis Scott', 4),
('Travis Scott', 5),
('Travis Scott', 6),
('Travis Scott', 7),
('Travis Scott', 8),
('Travis Scott', 9),
('Travis Scott', 10),
('Travis Scott', 11),
('Travis Scott', 12),
('Travis Scott', 13),
('Travis Scott', 14),
('Travis Scott', 15),
('Travis Scott', 16),
('Travis Scott', 17);

-- Inserts for the SONG_SINGERS table
INSERT INTO SONG_SINGERS (PersonName, SongId) VALUES
('Travis Scott', 1),
('Travis Scott', 2),
('Travis Scott', 3),
('Travis Scott', 4),
('Travis Scott', 5),
('Travis Scott', 6),
('Travis Scott', 7),
('Travis Scott', 8),
('Travis Scott', 9),
('Travis Scott', 10),
('Travis Scott', 11),
('Travis Scott', 12),
('Travis Scott', 13),
('Travis Scott', 14),
('Travis Scott', 15),
('Travis Scott', 16),
('Travis Scott', 17);



-- Inserts for the PEOPLE table
INSERT INTO PEOPLE (PersonName, BirthYear) VALUES
('Drake', 1986),
('Michael Jackson', 1958),
('Paul Anka', 1941),
('Noel Cadastre', NULL),
('Noah "40" Shebib', NULL),
('PARTYNEXTDOOR', NULL),
('Ty Dolla $ign', NULL),
('Static Major', 1974),
('James Fauntleroy', NULL),
('Mariah Carey', 1969),
('Big Freedia', 1978),
('JAY-Z', 1969),
('Nicki Minaj', 1982),
('Future', 1983),
('James Smith', NULL),
('Tyrone William Griffin Jr.', NULL),
('Kenneth "Babyface" Edmonds', 1959),
('Graham Nash', 1942),
('Oliver El-Khatib', NULL),
('Michael Gazzo', NULL),
('Stéphane Mgebrishvili', NULL);

-- Inserts for the ALBUMS table
INSERT INTO ALBUMS (AlbumTitle, AlbumYear) VALUES ('Scorpion', 2018);

-- Inserts for the SONGS table
INSERT INTO SONGS (SongTitle, SongYear) VALUES
('Survival', 2018),
('Nonstop', 2018),
('Elevate', 2018),
('Emotionless', 2018),
('God`s Plan', 2018),
('I`m Upset', 2018),
('8 Out Of 10', 2018),
('Mob Ties', 2018),
('Can`t Take A Joke', 2018),
('Sandra`s Rose', 2018),
('Talk Up', 2018),
('Is There More', 2018),
('Peak', 2018),
('Summer Games', 2018),
('Jaded', 2018),
('Nice For What', 2018),
('Finesse', 2018),
('Ratchet Happy Birthday', 2018),
('That`s How You Feel', 2018),
('Blue Tint', 2018),
('In My Feelings', 2018),
('Don`t Matter To Me', 2018),
('After Dark', 2018),
('Final Fantasy', 2018),
('March 14', 2018);

-- Inserts for the ALBUM_SONGS table
INSERT INTO ALBUM_SONGS (AlbumId, TrackId, SongId) VALUES
(2, 1, 18),
(2, 2, 19),
(2, 3, 20),
(2, 4, 21),
(2, 5, 22),
(2, 6, 23),
(2, 7, 24),
(2, 8, 25),
(2, 9, 26),
(2, 10, 27),
(2, 11, 28),
(2, 12, 29),
(2, 13, 30),
(2, 14, 31),
(2, 15, 32),
(2, 16, 33),
(2, 17, 34),
(2, 18, 35),
(2, 19, 36),
(2, 20, 37),
(2, 21, 38),
(2, 22, 39),
(2, 23, 40),
(2, 24, 41),
(2, 25, 42);

-- Inserts for the SONG_AUTHORS table
INSERT INTO SONG_AUTHORS (PersonName, SongId) VALUES
('Drake', 18),
('Drake', 19),
('Drake', 20),
('Drake', 21),
('Drake', 22),
('Drake', 23),
('Drake', 24),
('Drake', 25),
('Drake', 26),
('Drake', 27),
('Drake', 28),
('Drake', 29),
('Drake', 30),
('Drake', 31),
('Drake', 32),
('Drake', 33),
('Drake', 34),
('Drake', 35),
('Drake', 36),
('Drake', 37),
('Drake', 38),
('Drake', 39),
('Drake', 40),
('Drake', 41),
('Drake', 42);

-- Inserts for the SONG_SINGERS table
INSERT INTO SONG_SINGERS (PersonName, SongId) VALUES
('Drake', 18),
('Drake', 19),
('Drake', 20),
('Drake', 21),
('Drake', 22),
('Drake', 23),
('Drake', 24),
('Drake', 25),
('Drake', 26),
('Drake', 27),
('Drake', 28),
('Drake', 29),
('Drake', 30),
('Drake', 31),
('Drake', 32),
('Drake', 33),
('Drake', 34),
('Drake', 35),
('Drake', 36),
('Drake', 37),
('Drake', 38),
('Drake', 39),
('Drake', 40),
('Drake', 41),
('Drake', 42);



-- Inserts for the PEOPLE table
INSERT INTO PEOPLE (PersonName, BirthYear) VALUES
('Travis Scott', 1991),
('Kanye West', 1977),
('Allen Ritter', NULL),
('Mike Dean', NULL),
('Metro Boomin', 1993),
('Sonny Digital', NULL),
('WondaGurl', NULL),
('Illangelo', NULL),
('DJ Dahi', NULL),
('Zach Nahome', NULL),
('Bun B', 1973),
('Juicy J', 1975),
('Swae Lee', NULL),
('Chief Keef', 1995),
('The Weeknd', NULL),
('2 Chainz', 1977),
('Quavo', 1991),
('Young Thug', 1991),
('Justin Bieber', 1994),
('T.I.', 1980),
('Future', 1983),
('Schoolboy Q', 1986),
('Big Buck$', NULL);

-- Inserts for the ALBUMS table
INSERT INTO ALBUMS (AlbumTitle, AlbumYear) VALUES ('Rodeo', 2015);

-- Inserts for the SONGS table
INSERT INTO SONGS (SongTitle, SongYear) VALUES
('Pornography', 2015),
('Oh My Dis Side', 2015),
('3500', 2015),
('Wasted', 2015),
('90210', 2015),
('Pray 4 Love', 2015),
('Nightcrawler', 2015),
('Piss On Your Grave', 2015),
('Antidote', 2015),
('Impossible', 2015),
('Maria Im Drunk', 2015),
('Flying High', 2015),
('I Can Tell', 2015),
('Apple Pie', 2015),
('Ok Alright', 2015);

-- Inserts for the ALBUM_SONGS table
INSERT INTO ALBUM_SONGS (AlbumId, TrackId, SongId) VALUES
(3, 1, 43),
(3, 2, 44),
(3, 3, 45),
(3, 4, 46),
(3, 5, 47),
(3, 6, 48),
(3, 7, 49),
(3, 8, 50),
(3, 9, 51),
(3, 10, 52),
(3, 11, 53),
(3, 12, 54),
(3, 13, 55),
(3, 14, 56),
(3, 15, 57);

-- Inserts for the SONG_AUTHORS table
INSERT INTO SONG_AUTHORS (PersonName, SongId) VALUES
('Travis Scott', 43),
('Travis Scott', 44),
('Travis Scott', 45),
('Travis Scott', 46),
('Travis Scott', 47),
('Travis Scott', 48),
('Travis Scott', 49),
('Travis Scott', 50),
('Travis Scott', 51),
('Travis Scott', 52),
('Travis Scott', 53),
('Travis Scott', 54),
('Travis Scott', 55),
('Travis Scott', 56),
('Travis Scott', 57);

-- Inserts for the SONG_SINGERS table
INSERT INTO SONG_SINGERS (PersonName, SongId) VALUES
('Travis Scott', 43),
('Travis Scott', 44),
('Travis Scott', 45),
('Travis Scott', 46),
('Travis Scott', 47),
('Travis Scott', 48),
('Travis Scott', 49),
('Travis Scott', 50),
('Travis Scott', 51),
('Travis Scott', 52),
('Travis Scott', 53),
('Travis Scott', 54),
('Travis Scott', 55),
('Travis Scott', 56),
('Travis Scott', 57);
